export const WORK_ACTIVITIES = [
  [
    { category: 'e', label: 'going to the office' },
    { category: 'i', label: 'research job' },
    { category: 'r', label: 'construction and engineering' },
    { category: 'a', label: 'creative photography' },
  ],
  [
    { category: 'e', label: 'auctioneer' },
    { category: 's', label: 'teacher' },
    { category: 'r', label: 'mechanic' },
    { category: 'i', label: 'chemist' },
  ],
  [
    { category: 'c', label: 'monitor and record' },
    { category: 'e', label: 'sell and convince' },
    { category: 'a', label: 'design and paint' },
    { category: 's', label: 'help and care' },
  ],
  [
    { category: 's', label: 'social worker' },
    { category: 'c', label: 'administrator' },
    { category: 'r', label: 'fire fighter' },
    { category: 'e', label: 'manager' },
  ],
  [
    { category: 'a', label: 'jewelry creation' },
    { category: 's', label: 'guide children' },
    { category: 'i', label: 'medical diagnostics' },
    { category: 'c', label: 'take notes' },
  ],
  [
    { category: 'a', label: 'sketch and design' },
    { category: 'r', label: 'mobile mechanic' },
    { category: 's', label: 'help disabled' },
    { category: 'e', label: 'business manager' },
  ],
  [
    { category: 'i', label: 'study' },
    { category: 'a', label: 'styling and decorating' },
    { category: 'e', label: 'close business deals' },
    { category: 'r', label: 'fix it' },
  ],
  [
    { category: 's', label: 'social counselor' },
    { category: 'i', label: 'molecular scientist' },
    { category: 'c', label: 'accountant' },
    { category: 'r', label: 'veterinarian' },
  ],
  [
    { category: 'e', label: 'chairman' },
    { category: 'c', label: 'administration' },
    { category: 'i', label: 'gain knowledge' },
    { category: 'a', label: 'landscape architecture' },
  ],
  [
    { category: 'r', label: 'dental technician' },
    { category: 'r', label: 'host' },
    { category: 'a', label: 'draw' },
    { category: 's', label: 'information clerk' },
  ],
  [
    { category: 'c', label: 'controller' },
    { category: 'e', label: 'stockbroker' },
    { category: 'i', label: 'data analyst' },
    { category: 'r', label: 'engineer' },
  ],
  [
    { category: 'i', label: 'science' },
    { category: 'r', label: 'tools' },
    { category: 's', label: 'medical support' },
    { category: 'a', label: 'arts and drama' },
  ],
  [
    { category: 'r', label: 'logical reasoning' },
    { category: 'c', label: 'sorting and organizing' },
    { category: 'e', label: 'give directions' },
    { category: 's', label: 'to teach and explain' },
  ],
  [
    { category: 's', label: 'elderly care' },
    { category: 'e', label: 'estate agent' },
    { category: 'a', label: 'fashion designer' },
    { category: 'r', label: 'problem solving' },
  ],
  [
    { category: 'r', label: 'electronics' },
    { category: 'a', label: 'creative writing' },
    { category: 'c', label: 'archiving' },
    { category: 'e', label: 'salesperson' },
  ],
];
